[connections.gsheets_belem]
spreadsheet = "https://docs.google.com/spreadsheets/d/1D-rTqEaTIwAR-aBE52CDJVQUXYGoU3VoEXDO1k-oK-8/edit?gid=0"

[connections.gsheets_castanhal]
spreadsheet = "https://docs.google.com/spreadsheets/d/1mvC7unpB-4oPWxxIJC41b4wvDXNQDKv3NWaTLFUG8mE/edit?gid=0"

[connections.gsheets_barcarena]
spreadsheet = "https://docs.google.com/spreadsheets/d/1xtb16_q2R-HO8ZVbtBjrWdpjiaYTs8KLKkpFXKvyBy0/edit?gid=0"
